Simple transfer (#808)
* Merge branch 'action-test' of github.com:openziti/ziti into simple-transfer-test

* added metricbeat initialization

* updates to the simple network testing

* update zitilab and fablad deps and integrate env variables

* removed incorrect file

* move env up to top

* added run and test

* mod tidy

* mod got out of sync

* remove influx logging from ziti-probe due to being removed from metrics

* add ls to see why simple-transfer isnt built

* dig deeper

* need to copy not move

* back to release dir

* might need to sudo

* mke files executable

* bootsrap from correct directory

* add extra restart to confirm network spins up

* add retry for inrastructure

* build correct binaries

* add build ignore ot stages as well

* don't return error after successful retry

* fix err assign

* update zitilab version

* removed local testing paths

* update configs and env variables

* added env prepend

* remove build number for debugging

* add different formatting

* updated build/run number

* paren in incorrect place

* added specific version of metricbeat to install

* flip back correct ziti loc

* removed builds for mac & windows

* Removed test build for mac & windows

* remove ziti-probe

* flip ziti test to run alongside mac & windows builds

* remove unneeded needs

* remove for sanity check

* remove old uploads

* remove space

* setup ziti version properly

* remove zitilab testing to confirm running

* try removing all changes?

* remove even comments?

* I dont understand

* revert

* start from scratch. Small increments.

* simplify first job?

* try spearating build and publish

* run all 3 builds at the same time

* missed env variables

* update to run zitilab tests

* corrected dirs

* fixing ziti root

* redo build in publish step

* applied pr comments

* add in mkdir and remove buildint test binaries in publish step

* forgot to remove move

* update linux build requirement to 1.19

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,9 +11,19 @@ on:
 env:
   GOFLAGS: "-trimpath"
   GOX_OUTPUT: "release/{{.Arch}}/{{.OS}}/{{.Dir}}"
+  GOX_TEST_OUTPUT: "test/{{.Arch}}/{{.OS}}/bin/{{.Dir}}"
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  AWS_DEFAULT_REGION: "us-east-2"
   gh_ci_key: ${{ secrets.GH_CI_KEY }}
+  CONSUL_ENCRYPTION_KEY: ${{ secrets.CONSUL_ENCRYPTION_KEY }}
+  ELASTIC_ENDPOINT: ${{ secrets.ELASTIC_ENDPOINT }}
+  ELASTIC_USERNAME: ${{ secrets.ELASTIC_USERNAME }}
+  ELASTIC_PASSWORD: ${{ secrets.ELASTIC_PASSWORD }}
+  CONSUL_ENDPOINT: ${{ secrets.CONSUL_ENDPOINT }}
+  CONSUL_AGENT_CERT: ${{ secrets.CONSUL_AGENT_CERT }}
+  BUILD_NUMBER: ${{ format('{0}-{1}-{2}', github.run_id, github.run_number, github.run_attempt) }}
+
 
 jobs:
   mac-os-build:
@@ -78,7 +88,105 @@ jobs:
           retention-days: 5
 
   linux-build:
-    name: Build and Publish Linux Binaries and Docker Image
+    name: Build Linux Binaries
+    runs-on: ubuntu-20.04
+    outputs:
+      ziti-version: ${{ steps.get_version.outputs.ziti-version }}
+    steps:
+      - name: Git Checkout
+        uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+
+      - name: Install Go
+        uses: actions/setup-go@v3
+        with:
+          go-version: '1.19.x'
+
+      - name: Install Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: '3.7'
+
+      - name: Install Ziti CI
+        uses: netfoundry/ziti-ci@v1
+
+      - name: Build and Test
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ziti_ci_gpg_key: ${{ secrets.ZITI_CI_GPG_KEY }}
+          ziti_ci_gpg_key_id: ${{ secrets.ZITI_CI_GPG_KEY_ID }}
+        run: |
+          mkdir -p release/amd64/linux/bin
+          sudo apt-get update
+          sudo apt-get -yq install gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf gcc-aarch64-linux-gnu
+          $(go env GOPATH)/bin/ziti-ci configure-git
+          $(go env GOPATH)/bin/ziti-ci generate-build-info common/version/info_generated.go version
+          go install github.com/mitchellh/gox@latest
+          $(go env GOPATH)/bin/gox -cgo -os=linux -arch=amd64 -output=release/amd64/linux/bin ./...
+
+          go build -tags=all,tests -o release/amd64/linux/bin ./...
+          
+      - name: Compute the Ziti Version String for CI Jobs
+        id: get_version
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_REF: ${{ github.ref }}
+          GITHUB_RUN_ID: ${{ github.run_id }}
+        run: |
+          ZITI_VERSION="$($(go env GOPATH)/bin/ziti-ci -q get-current-version)"
+          # drop the leading 'v', if any
+          ZITI_VERSION=${ZITI_VERSION#v}
+          if ! [[ "${ZITI_VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            # fail the job because we could not obtain the current version from ziti-ci
+            echo "ERROR: ZITI_VERSION=${ZITI_VERSION}"
+            exit 1
+          elif [[ "${GITHUB_REF}" =~ ^refs/heads/(release-v|main$) ]]; then
+            # Set output parameters for release branches
+            echo "DEBUG: ZITI_VERSION=${ZITI_VERSION}"
+            echo ::set-output name=ziti-version::${ZITI_VERSION}
+          else
+            # Append build / run number for non-release refs
+            ZITI_VERSION="${ZITI_VERSION}-${GITHUB_RUN_ID}"
+            echo "DEBUG: ZITI_VERSION=${ZITI_VERSION}"
+            echo ::set-output name=ziti-version::${ZITI_VERSION}
+          fi
+
+      - name: Create Zitilab Bindings
+        run: |
+          mkdir ~/.fablab
+          touch ~/.fablab/bindings.yml
+          echo "credentials:"           >> ~/.fablab/bindings.yml
+          echo "  aws:"                 >> ~/.fablab/bindings.yml
+          echo "    managed_key: true"  >> ~/.fablab/bindings.yml
+          echo "  edge:"                >> ~/.fablab/bindings.yml
+          echo "    username: admin"    >> ~/.fablab/bindings.yml
+          echo "    password: admin"    >> ~/.fablab/bindings.yml
+          echo "  influxdb:"            >> ~/.fablab/bindings.yml
+          echo "    username: fablab"   >> ~/.fablab/bindings.yml
+          echo "    password: fablab"   >> ~/.fablab/bindings.yml
+
+      - name: Test Ziti Command
+        env:
+          ZITI_ROOT: release/amd64/linux/
+          ZITI_VERSION: ${{ steps.get_version.outputs.ziti-version }}
+        run: |
+          release/amd64/linux/bin/simple-transfer create
+          release/amd64/linux/bin/simple-transfer up
+          release/amd64/linux/bin/simple-transfer run
+
+      - name: Test Ziti Command Teardown
+        if: always()
+        env:
+            ZITI_ROOT: release/amd64/linux/
+        run: |
+          release/amd64/linux/bin/simple-transfer dispose
+          release/amd64/linux/bin/simple-transfer clean
+
+      # END linux-build-steps
+
+  publish:
+    name: Publish Binaries and Docker Image
     runs-on: ubuntu-20.04
     needs: [ mac-os-build, windows-build ]
     outputs:
@@ -116,7 +224,7 @@ jobs:
           $(go env GOPATH)/bin/gox -cgo -os=linux -arch=amd64 -output=$GOX_OUTPUT ./...
           CC=arm-linux-gnueabihf-gcc $(go env GOPATH)/bin/gox -cgo -os=linux -arch=arm -output=$GOX_OUTPUT ./...
           CC=aarch64-linux-gnu-gcc   $(go env GOPATH)/bin/gox -cgo -os=linux -arch=arm64 -output=$GOX_OUTPUT ./...
-
+      
       - name: Download darwin release artifact
         uses: actions/download-artifact@v2
         with:
@@ -225,8 +333,6 @@ jobs:
           platforms: linux/amd64,linux/arm/v7,linux/arm64
           push: true
           tags: ${{ steps.tagprep.outputs.tags }}
-
-      # END linux-build-steps
 
   smoketest:
     # BEGIN smoketest-job
